FROM maven:3.9-eclipse-temurin-25-alpine AS build
WORKDIR /build
COPY api/ .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY --from=build /build/presentacion/target/presentacion-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
